name: "Feature Request"
description: "Suggest a new idea or improvement"
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an improvement!

  - type: dropdown
    id: area
    attributes:
      label: Area of Enhancement
      description: What part of the extension is this related to?
      options:
        - Commands
        - Sidebar
        - Snippet Editor
        - File Management
        - Git Integration
        - Configuration Settings
        - Other

  - type: textarea
    id: summary
    attributes:
      label: What would you like to see improved?
      placeholder: "Describe the feature or enhancement you'd like to propose."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
        - Critical